name: Caller workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "environment"
        type: environment
        required: true
jobs:
  init:
    runs-on: ubuntu-latest
    name: "my test"
    environment: ${{ inputs.environment }}
    steps:
      - name: "Print vars"
        run: |
          echo "${{ vars.ENVIRONMENT }}"
  another:
    needs: [ init ]
    uses: ./.github/workflows/my_workflow.yml
