name: Call Test inputs context
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        required: true
        options:
         - 'dev'
         - 'qa'
         - 'prod'
        default: 'dev'
  workflow_call:
jobs:
  build:
    uses: ./.github/workflows/test-inputs.yml
    with:
      test: true
    secrets: inherit
