name: My workflow
on:
  workflow_call:
    
jobs:
  init:
    runs-on: ubuntu-latest
    name: "this is a test"
    steps:
      - name: "print"
        run: |
          echo "${{ vars.ENVIRONMENT }}"
