name: Test Concurrency
on:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello, I am sleeping"
        sleep 60
        echo "Bye!"
        
