name: Write Secrets
on:
  workflow_dispatch:
    inputs:
      key:
        description: key
        type: string
        required: true
      value:
        description: value
        type: string
        required: true
      secret:
        description: secret
        type: boolean
        required: false
        default: false
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Write to GitHub secrets/vars
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            console.log(context);
            if (${{ inputs.secret }}) {
                console.log('Process secrets');
            } else {
                github.rest.actions.createEnvironmentVariable({
                    repository_id: context.payload.repository.id,
                    environment_name: 'dev',
                    name: '${{ inputs.key }}',
                    value: '${{ inputs.value }}'
                });
            }
